---
title: "Creating Finalized Maps"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(raster)
library(tidyverse)
library(sf)
library(here)
library(fasterize)
library(stringr)
library(janitor)
library(rgdal)
library(ggmap)
library(tmap)
```

#### **STEP 1: Read in Mozambique EEZ and Shapefile**
```{r}
## read in MZ EEZ tif
mz_rast_id <- raster(here("set_up/final_rasters/mz_eez_templates/mz_rast_id.tif"))

## Grab Moz Exclusive Economic Zone (EEZ) shapefile from local computer
mz_eez_path <- 'G:/group_project/data/mz_eez'
mz_shape <- list.files(mz_eez_path, full.names = TRUE) 

mz_eez_sf <- sf::read_sf(mz_shape[6])

### read in existing mpas raster
exist_mpas <- raster(here("set_up", "final_rasters", "planning_unit", "exist_mpa.tif"))

### plot to make sure it looks okay
plot(exist_mpas)
```


#### **STEP 2: Create a function that makes an interactive map**
```{r}
## create function
create_map <- function(final_raster, mpas){

  final_raster[final_raster == 0] <- NA
  
  tmap_mode("view") # Set to interactive viewing

  tm_shape(final_raster)+
    tm_raster(final_raster[1], palette="dodgerblue3", legend.show = F)+
  tm_shape(mz_eez_sf)+
    tm_borders("black", lwd = .5) +
  tm_basemap("Esri.WorldGrayCanvas")+
    tm_shape(exist_mpas)+
  tm_raster(exist_mpas[1], palette = "deeppink2", legend.show = F)+
    tm_add_legend("fill",
              col = c("dodgerblue3", "deeppink2"),
	            border.col = "black",
	            labels = c('Suggested Areas','Existing MPAs'),
	            title="Prioritization Model")
}

## create function to calculate the percentage of protected area
calc_percent_protected <- function(final_raster, x){
  final_raster_df <- rasterToPoints(final_raster) %>%
  as.data.frame() %>%
  group_by({{x}}) %>%
  summarise(count = n()) %>%
  mutate(total = (count/sum(count)*100))
}

```
#### **Creating maps for each scenario**

Scenario 1: Area at 20% and BLM at 0 and 0.0000001
```{r}
### create file path to read in final raster
area_path <- here("final_results", "scenario_1_area")
area_files <- list.files(area_path, full.names = TRUE)

area_20_blm0.000001 <- raster(area_files[3])
plot(area_20_blm0.000001)

percent_area_20_blm0.000001 <- calc_percent_protected(area_20_blm0.000001, sprob_area_20_6hr_blm0.000001)

area_20_blm0 <- raster(area_files[4])
plot(area_20_blm0)

percent_area_20_blm0 <- calc_percent_protected(area_20_blm0, sprob_area_20_6hr_blm0)


## create interactive maps for area sc
area_20_blm0.000001_map <- create_map(area_20_blm0.000001, exist_mpas)
area_20_blm0_map <- create_map(area_20_blm0, exist_mpas)

tmap_save(area_20_blm0.000001_map, filename = "final_results/final_maps/area_20_blm0.000001_map.html")
tmap_save(area_20_blm0_map, filename = "final_results/final_maps/area_20_blm0_map.html")
```

Scenario 2: Artisanal at 20% and BLM at 0 and 0.0000001
```{r}
### create file path to read in final raster
artisanal_path <- here("final_results", "scenario_2_artisanal")
artisanal_files <- list.files(artisanal_path, full.names = TRUE)

artisanal_20_blm0.000001 <- raster(artisanal_files[3])
plot(artisanal_20_blm0.000001)

percent_artisanal_20_blm0.000001 <- calc_percent_protected(artisanal_20_blm0.000001, sprob_artisanal_20_6hr_blm0.000001)

artisanal_20_blm0 <- raster(artisanal_files[4])
plot(artisanal_20_blm0)

percent_artisanal_20_blm0 <- calc_percent_protected(artisanal_20_blm0, sprob_artisanal_20_6hr_blm0)

## create interactive maps for artisanal sc
artisanal_20_blm0.000001_map <- create_map(artisanal_20_blm0.000001, exist_mpas)
artisanal_20_blm0_map <- create_map(artisanal_20_blm0, exist_mpas)

tmap_save(artisanal_20_blm0.000001_map, filename = "final_results/final_maps/artisanal_20_blm0.000001_map.html")
tmap_save(artisanal_20_blm0_map, filename = "final_results/final_maps/artisanal_20_blm0_map.html")
```

Scenario 3: Industrial at 20% and BLM at 0 and 0.0000001
```{r}
### create file path to read in final raster
industrial_path <- here("final_results", "scenario_3_industrial")
industrial_files <- list.files(industrial_path, full.names = TRUE)

industrial_20_blm0.000001 <- raster(industrial_files[3])
plot(industrial_20_blm0.000001)

percent_industrial_20_blm0.000001 <- calc_percent_protected(industrial_20_blm0.000001, sprob_industrial_20_6hr_blm0.000001)

industrial_20_blm0 <- raster(industrial_files[4])
plot(industrial_20_blm0)

percent_industrial_20_blm0 <- calc_percent_protected(industrial_20_blm0, sprob_industrial_20_6hr_blm0)

## create interactive maps for industrial sc
industrial_20_blm0.000001_map <- create_map(industrial_20_blm0.000001, exist_mpas)
industrial_20_blm0_map <- create_map(industrial_20_blm0, exist_mpas)

tmap_save(industrial_20_blm0.000001_map, filename = "final_results/final_maps/industrial_20_blm0.000001_map.html")
tmap_save(industrial_20_blm0_map, filename = "final_results/final_maps/industrial_20_blm0_map.html")
```


Scenario 4: Combined at 20% and BLM at 0 and 0.0000001
```{r}
### create file path to read in final raster
combined_path <- here("blm_sensitivity")
combined_files <- list.files(combined_path, full.names = TRUE)

combined_20_blm0.000001 <- raster(combined_files[4])
plot(combined_20_blm0.000001)

percent_combined_20_blm0.000001 <- calc_percent_protected(combined_20_blm0.000001, sprob_combined_20_6hr_blm0.000001)

combined_20_blm0 <- raster(combined_files[14])
plot(combined_20_blm0)

percent_combined_20_blm0 <- calc_percent_protected(combined_20_blm0, sprob_combined_20_6hr_blm0)

## create interactive maps for combined sc
combined_20_blm0.000001_map <- create_map(combined_20_blm0.000001, exist_mpas)
combined_20_blm0_map <- create_map(combined_20_blm0, exist_mpas)

tmap_save(combined_20_blm0.000001_map, filename = "final_results/final_maps/combined_20_blm0.000001_map.html")
tmap_save(combined_20_blm0_map, filename = "final_results/final_maps/combined_20_blm0_map.html")
```


Scenario 5: Inverse at 20% and BLM at 0 and 0.0000001
```{r}
### create file path to read in final raster
inverse_path <- here("final_results", "scenario_5_inverse")
inverse_files <- list.files(inverse_path, full.names = TRUE)

inverse_20_blm0.000001 <- raster(inverse_files[3])
plot(inverse_20_blm0.000001)

percent_inverse_20_blm0.000001 <- calc_percent_protected(inverse_20_blm0.000001, sprob_combined_inverse_20_6hr_blm0.000001)

inverse_20_blm0 <- raster(inverse_files[4])
plot(inverse_20_blm0)

percent_inverse_20_blm0 <- calc_percent_protected(inverse_20_blm0, sprob_combined_inverse_20_6hr_blm0)

## create interactive maps for inverse sc
inverse_20_blm0.000001_map <- create_map(inverse_20_blm0.000001, exist_mpas)
inverse_20_blm0_map <- create_map(inverse_20_blm0, exist_mpas)

tmap_save(inverse_20_blm0.000001_map, filename = "final_results/final_maps/inverse_20_blm0.000001_map.html")
tmap_save(inverse_20_blm0_map, filename = "final_results/final_maps/inverse_20_blm0_map.html")
```

#### Create maps of cost layers

```{r}
### create file path to read in final raster
cost_path <- here("set_up", "final_rasters", "costs")
cost_files <- list.files(cost_path, full.names = TRUE)

area_cost <- raster(cost_files[1])
plot(area_cost)

# inverse_20_blm0 <- raster(inverse_files[4])
# plot(inverse_20_blm0)
# 
# ## create interactive maps for inverse sc
# inverse_20_blm0.000001_map <- create_map(inverse_20_blm0.000001, exist_mpas)
# inverse_20_blm0_map <- create_map(inverse_20_blm0, exist_mpas)
# 
# tmap_save(inverse_20_blm0.000001_map, filename = "final_results/final_maps/inverse_20_blm0.000001_map.html")
# tmap_save(inverse_20_blm0_map, filename = "final_results/final_maps/inverse_20_blm0_map.html")
```
















