---
title: "scenario_6_management"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(raster)
library(tidyverse)
library(sf)
library(here)
library(fasterize)
library(stringr)
library(janitor)
library(prioritizr)
library(rgdal)
library(gurobi)
```

### **STEP 1: Assign planning units, cost layer, and conservation feature**

#### Planning Unit
```{r}
### reading in the baseline MZ EEZ raster (with cell ids) 
pu_6 <- raster(here("set_up", "final_rasters", "mz_eez_templates", "mz_rast_id.tif"))

### plot to make sure it looks okay
plot(pu_6)
```

#### Cost Layer
```{r}
### pull in the cost layer created in setup step 9
cost_distance <- raster(here("set_up", "final_rasters", "costs", "dist_rast.tif"))

### plot to make sure it looks okay
plot(cost_distance)
```

#### Conservation Features
This includes all species distributions and habitat rasters:
```{r}
### pull in species stack that we created in set-up step 3
features_stack_6 <- brick(here("set_up", "final_rasters", "conservation_features","all_features_stack.tif"))

### plot to make sure it looks okay
plot(features_stack_6)
```

### Additional Files (Locked-in & Locked-out)
```{r}
### read in existing mpas raster
exist_mpas_6 <- raster(here("set_up", "final_rasters", "planning_unit", "exist_mpa.tif"))

### plot to make sure it looks okay
plot(exist_mpas_6)
```

#### RUN 1: Baseline - 10% target, Boundary Penalty = 0 
```{r}
## Define the problem with the cost, conservation features, targets, locked in and locked out constraints using the minimum set objective
prob_management_10 <- problem(cost_distance, features = features_stack_6) %>%
  add_min_set_objective() %>%
  add_relative_targets(0.1) %>%
  add_locked_in_constraints(exist_mpas_6) %>%
  add_gurobi_solver(gap = 0.01, time_limit = 21600)

## Solve problem
sprob_management_10 <- solve(prob_management_10)

## Plot the solution to see what it looks like
plot(sprob_management_10,  main = c("Area- 10% Targets"))

## Save as tif
writeRaster(sprob_management_10, here("final_results", "scenario_6_management",  "sprob_management_10_6hr_blm0.tif"), overwrite = TRUE)
```

#### RUN 2: Baseline - 10% target, Boundary Penalty = 0.00001 
```{r}
## Define the problem with the cost, conservation features, targets, locked in and locked out constraints using the minimum set objective
prob_management_10_blm <- problem(cost_distance, features = features_stack_6) %>%
  add_min_set_objective() %>%
  add_relative_targets(0.1) %>%
  add_locked_in_constraints(exist_mpas_6) %>%
  add_gurobi_solver(gap = 0.01, time_limit = 21600) %>% 
  add_boundary_penalties(0.000001)

## Solve problem
sprob_management_10_blm <- solve(prob_management_10_blm)

## Plot the solution to see what it looks like
plot(sprob_management_10_blm,  main = c("Area- 10% Targets"))

## Save as tif
writeRaster(sprob_management_10_blm, here("final_results", "scenario_6_management",  "sprob_management_10_6hr_blm0.000001.tif"), overwrite = TRUE)
```