---
title: "species_status"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

#load packages
library(raster)
library(tidyverse)
library(sf)
library(here)
library(fasterize)
library(stringr)
library(janitor)
library(fasterize)
```


IUCN. (2018). The IUCN Red List of threatened species. Version 2018-1. Retrieved from http://www.iucnredlist.org

#### **STEP 1: Read in Mozambique EEZ and Shapefile**
```{r}
## read in MZ EEZ tif
mz_rast_id <- raster(here("set_up/final_rasters/mz_eez_templates/mz_rast_id.tif"))
plot(mz_rast_id)

## Grab Moz Exclusive Economic Zone (EEZ) shapefile from local computer
mz_eez_path <- 'G:/group_project/data/mz_eez'
mz_shape <- list.files(mz_eez_path, full.names = TRUE) 

mz_eez_sf <- sf::read_sf(mz_shape[6])

## check coordinate system
st_crs(mz_eez_sf)

## Add a buffer of 10 km to make sure cells on the outer edges of the EEZ are included
#mz_eez_buffer_sf <- sf::st_buffer(mz_eez_sf, dist = 10000)
```

#### **STEP 2: Read in IUCN CHONDRICHTHYES Shapefiles**
```{r}
### grab iucn data from local computer
iucn_path <- 'G:/group_project/data/updated_iucn'
iucn_shape <- list.files(iucn_path, full.names = TRUE) 

iucn_sf <- sf::read_sf(iucn_shape[9])

### create a dataframe to look at the different variables and remove geometry to speed it up
iucn_df <- iucn_sf %>%
  as.data.frame() %>% 
  select(-geometry)

```



```{r}
### reclassify status
risk_df <- iucn_sf  %>% 
  mutate(risk_level = case_when(category == "CR" ~3,
                          category == "EN" ~2,
                          category == "VU"~ 1))


### create dataframe that only contains species and changes to correct crs
thresher_shark <- risk_df %>%
  filter(binomial == "Alopias pelagicus") %>% 
  st_transform(., crs = st_crs(mz_eez_sf)) 

### check crs to make sure it matches
st_crs(thresher_shark)

### create a raster
thresher_shark_rast <- fasterize::fasterize(thresher_shark, mz_rast_id, field = "risk_level") %>%
  mask(mz_eez_sf)

### plot to see how it looks
plot(thresher_shark_rast)

```


```{r}
create_rast_status <- function(risk_df, species_name){
  outfile <- sprintf(here('set_up/final_rasters/conservation_features/iucn_species_status/species_%s.tif'), species_name)
  message('Processing species ', species_name, ' to create file ', outfile)

  species_df <- risk_df %>%
  filter(binomial == species_name) %>% 
  st_transform(., crs = st_crs(mz_eez_sf))

species_rast <- fasterize::fasterize(species_df, mz_rast_id, field = "risk_level") %>% 
  mask(mz_eez_sf)

writeRaster(species_rast, filename = outfile, overwrite = TRUE)

return('yay it works')

}

# dusky_shark_rast <- create_rast_status(risk_df, "Carcharhinus obscurus")
# plot(dusky_shark_rast)

```

```{r}
### create vector 
species_name <- c("Alopias pelagicus",
                 "Alopias superciliosus",
                 "Alopias vulpinus",
                 "Carcharhinus amblyrhynchos",
                 "Carcharhinus longimanus",
                 "Carcharhinus obscurus",
                 "Carcharodon carcharias",
                 "Isurus oxyrinchus",
                 "Isurus paucus",
                 "Carcharias taurus",
                 "Rhincodon typus",
                 "Sphyrna lewini",
                 "Sphyrna mokarran",
                 "Sphyrna zygaena",
                 "Stegostoma tigrinum",
                 "Mobula alfredi",
                 "Mobula birostris",
                 "Mobula kuhlii",
                 "Mobula mobular",
                 "Pristis pristis",
                 "Pristis zijsron",
                 "Rostroraja alba",
                 "Rhina ancylostoma",
                 "Acroteriobatus leucospilus")
```

```{r}
### create loop 
for (i in seq_along(species_name)) {
  create_rast_status(risk_df, species_name[i])
}
```

#### **STEP 8: Creating Species Stack** --must clear environment to run this chuck...
```{r}
### create file path to read in all 30 species tifs in 
species_status_path <- here("set_up", "final_rasters", "conservation_features", "iucn_species_status")
species_status_files <- list.files(species_status_path, full.names = TRUE)

### stack them (this includes the three that we manually created and saved in the same IUCN folder)
species_status_stack <- stack(species_status_files)

### plot to see how they look and make a data frame to double check
plot(species_status_stack)
species_status_stack_df <- as.data.frame(species_status_stack)

### write raster
writeRaster(species_status_stack, here('set_up/final_rasters/conservation_features/iucn_species_status/species_status_stack.tif'), options="INTERLEAVE=BAND",  overwrite = TRUE)
```




