---
title: "9_planning_unit"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}

#attach libraries
library(raster)
library(tidyverse)
library(sf)
library(here)
library(fasterize)
library(multiplex)
library(rio)
```

```{r}
mz_rast_pu <- raster(here("set_up", "final_rasters", "mz_eez_templates","mz_rast_id.tif"))
existing_mpa <- raster(here("set_up", "final_rasters", "planning_unit", "exist_mpas.tif"))
oil_rast <- raster(here("set_up", "final_rasters", "planning_unit", "oil_rigs.tif"))
ports_dist_rast <- raster(here("set_up", "final_rasters", "planning_unit", "port_dist_rast.tif")) 

```

```{r}
## Create raster stack of planning unit, existing MPA's, oil, and shipping lanes
pu_stack <- stack(mz_rast_pu, existing_mpa, oil_rast, ports_dist_rast)

## Create data frame from raster stack
pu_stack_df <- as.data.frame(pu_stack, xy = TRUE) %>%
  mutate_all(~replace(., is.na(.), 0))

## Use pivot longer to create the data frame that uses just one column 'Status' to indicate which planning units are longed in or out
pu_df <- pu_stack_df %>% mutate(status = case_when(exist_mpas == 1 ~ 2,
                                                   exist_mpas == 0 & oil_rigs == 0 ~ 0,
                                                   exist_mpas == 0 & oil_rigs == 1 ~ 3))

#new df with cell ids and status
pu_final <- pu_df %>% 
  rename(cost = port_dist_rast, id = mz_rast_id) %>% 
  select("id", "cost", "status", "x", "y")

#save as a csv
write_csv(pu_final, here("set_up", "csv_files", "pu_final.csv"))

#save as .dat file format
write_csv(pu_final, here("set_up", "dat_files", "pu_final.dat"))



```
