---
title: "7_oil_rigs"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

### load packages
library(raster)
library(tidyverse)
library(sf)
library(here)
library(fasterize)
library(janitor)
#library(tiff)

```

## *Script to prep oil rigs raster for planning unit input file*

### *STEP 1: Read in MZ EEZ rasters and oil rigs data*
```{r}
## Read in oil tif from local computer as a raster
oil_tif <- 'G:/group_project/Data/Oil_rigs/oil_rig_2013_halpern_et_al_2015_clipped.tif'

## Bring in MZ raster that was created in Script 1 with resolution 10000
mz_rast_id <- raster(here("set_up/final_rasters/mz_eez_templates/mz_rast_id.tif"))
```

### *STEP 2: Read in MZ EEZ shapefile to use as mask*
```{r}
## Grab Moz Exclusive Economic Zone (EEZ) shapefile from local computer
mz_eez_path <- 'G:/group_project/data/mz_eez'
mz_shape <- list.files(mz_eez_path, full.names = TRUE) 

mz_eez_sf <- sf::read_sf(mz_shape[6])

## check coordinate system
st_crs(mz_eez_sf)

## Add a buffer of 10 km to make sure cells on the outer edges of the EEZ are included
mz_eez_buffer_sf <- sf::st_buffer(mz_eez_sf, dist = 10000)
```

### *STEP 3: Create a raster*
```{r}
#create oil raster
oil_rast <- raster(oil_tif)

#create data frame from raster
# oil_df <- oil_rast %>%
#   rasterToPoints() %>%
#   as.data.frame() %>%
#   rename("status" = "oil_rig_2013_halpern_et_al_2015_clipped") %>% 
#   mutate(status = case_when(status %in% c("1") ~ "3")) %>% 
#   na.omit()

## Reproject the oil raster to match the Moz EEZ raster
oil_reproj <- raster::projectRaster(oil_rast, mz_rast_id, 
                                            res = 10000,
                                            method = 'ngb',
                                            crs = crs(mz_rast_id))

## Plot to see what it looks like
plot(oil_reproj)

## There are terrestrial oil projects included in this file so we will need to again maks it to the MZ EEZ
oil_rast_f <- mask(oil_reproj, mz_eez_buffer_sf) 

## Plot to make sure it looks good
plot(oil_rast_f)

#save new raster as a tif
writeRaster(oil_rast_f, here('set_up/final_rasters/planning_unit/oil_rigs.tif'), overwrite = TRUE)

```

Citations:
 - 
 
Outputs:
 -`oil_rigs` = raster of oil rigs within Mozambique EEZ at 10000m resolution

End script.
